export default {
    en: {
        welcome: 'Welcome to the testing system!',
        sphere: "English language testing system",
        information: "Information",
        start: "Start test",
        toTest: 'Go to the testing',
        testTopic: 'Test topic',
        input: 'Input question',
        topics: 'Topics',
        yourGroup: 'Your group',
        group: 'Group',
        groups: 'Groups',
        choose: 'Choose your group and test',
        result: 'Your result:',
        detail: 'More details',
        no_inf: "No data",
        all: "All",
        name: "Your name",
        userName: "User name",
        email: "Your Email",
        dashboard: "Dashboard",
        management: "Dashboard",
        dashboard_welcome: "Welcome to the site's dashboard. Select the desired action from the left menu.",
        total_tests: "Total tests",
        total_topics: "Total topics",
        total_links: "Total links to third-party resources",
        total_users: "Registered users",
        avail_pass: "Available for passage",
        cancel: "Cancel",
        send: "Send",
        attemptsExc: 'Number of attempts to pass the test exceeded',
        attempts: 'Number of attempts',
        userCanNotPass: 'This user can not take the current test',
        expired: 'Test time expired',
        stats: 'Statistics',
        correct: 'Correct',
        correct_ans: 'Correct answer',
        incorrect: 'Incorrect',
        duration: 'Duration',
        show: 'Show',
        print: 'Print',
        grInform: 'Graphic information',
        average: 'Average score by level:',
        dateTime: 'Date and time of work',
        notFound: "OOPS! Not found",
        notFoundMsg: "Sorry, the requested page does not exist",
        return: "Return to the main page",
        site_name: "English language testing system",
        login: "Login",
        users: "Users",
        user: "User",
        home: "Home",
        title:"Title",
        descr:"Description",
        available:"Available",
        published:"Published",
        yes:"Yes",
        no:"No",
        register: "Sign up",
        logOut: "Logout",
        password: "Password",
        level: "Level",
        levels: "Levels",
        score: "Score",
        quest: 'Question',
        answer: 'Answer',
        variants: 'Answer options',
        userTip: 'User answer',
        sources: 'Sources',
        source: 'Source',
        max: "To the max",
        perf: "Academic performance",
        test: "Test",
        tests: "Tests",
        date: "Date",
        download: "Download",
        password_more: "Password again",
        forgot: "Forgot Your Password?",
        resetPas: "Password reset",
        reset: "Reset",
        close: "Close",
        remove_ans: "Delete answer",
        save: "Save",
        loading: "Processing...",
        contact: "Contact",
        admin: "administrator",
        adm: "Administrator",
        blocked: "Banned",
        fullName: "Full name",
        link: "Link",
        links: "Links",
        add: "Create",
        add_answer: "Add answer variant",
        access_d: "Access denied",
        info_changed: "The information has been successfully updated",
        info_deleted: "The information has been successfully removed",
        email_sent: "The information has been successfully sent to your Email",
        error_group: "Choose your group",
        error_auth: 'Error! You are not authorized!',
        error_email: 'Incorrect email address entered',
        error_pass_length: "Password must not be less than 6 characters",
        error_pass_match: "The passwords entered do not match.",
        error_confirm_pass: "Confirm password",
        error_email_exists: "Entered Email address already exists",
        error_no_user: "There is no user with such data.",
        error_login: "Invalid username. Special characters are not allowed in the username, or the length is less than 3 characters",
        error_try_later: "Something went wrong ... Please try again later",
        failing: 'Failing grade',
        good: 'Good grade',
        satisfactory: 'Satisfactory grade',
        excellent: 'Excellent grade',
        errors: {
            title: "Title",
            source: "Source",
            description: "Description",
            task: "Task",
            answer: "Answer",
            username: "Username",
            email: "Email",
            level: "Level",
            password: "Password",
            string: 'must be a string',
            required: 'is required',
            incorrect: 'is incorrect',
            title_string: '@:errors.title @:errors.string',
            source_string: '@:errors.source @:errors.string',
            source_required: '@:errors.source @:errors.required',
            description_string: '@:errors.description @:errors.string',
            task_string: '@:errors.task @:errors.string',
            answer_string: '@:errors.answer @:errors.string',
            title_required: '@:errors.title @:errors.required',
            description_required: '@:errors.description @:errors.required',
            username_required: '@:errors.username @:errors.required',
            task_required: '@:errors.task @:errors.required',
            level_required: '@:errors.level @:errors.required',
            answer_required: '@:errors.answer @:errors.required',
            username_incorrect: '@:errors.username @:errors.incorrect',
            email_incorrect: '@:errors.email @:errors.incorrect',
        }
    },
    ua: {
        welcome: "Ласкаво просимо до системи тестування!",
        sphere: "Система тестування з англійської мови",
        information: "Інформація",
        start: "Розпочати тест",
        toTest: 'До тестування',
        testTopic: 'Тема тесту',
        input: 'Питання на введення',
        topics: 'Теми',
        yourGroup: 'Ваша група',
        group: 'Група',
        groups: 'Групи',
        choose: 'Виберіть Вашу групу та тему тесту',
        result: 'Ваш результат:',
        detail: 'Детальніше',
        no_inf: "Немає інформації",
        all: "Усе",
        name: "Ваше ім\'я",
        userName: "Ім\'я користувача",
        email: "Ваш Email",
        dashboard: "Панель управління",
        dashboard_welcome: "Ласкаво просимо до панелі управління сайту. Виберіть потрібну дію з меню ліворуч.",
        management: "Управління",
        total_tests: "Всього тестів",
        total_topics: "Всього тем",
        total_links: "Всього посилань на сторонні ресурси",
        total_users: "Зареєстрованих користувачів",
        avail_pass: "Доступних для проходження",
        cancel: "Скасувати",
        send: "Надіслати",
        userCanNotPass: 'Цей користувач не може проходити поточний тест',
        attemptsExc: 'Кількість спроб для проходження тесту перевищено',
        attempts: 'Кількість спроб',
        expired: 'Час тесту закінчився',
        stats: 'Статистика',
        correct: 'Вірних',
        correct_ans: 'Вірна відповідь',
        incorrect: 'Невірних',
        duration: 'Тривалість',
        show: 'Показати',
        print: 'Роздрукувати',
        grInform: 'Графічна інформація',
        average: 'Середня оцінка за рівнем:',
        dateTime: 'Дата і час роботи',
        notFound: "OOPS! Не знайдено",
        notFoundMsg: "На жаль, запитувана сторінка не існує",
        return: "Повернутися на головну сторінку",
        site_name: "Система тестування з англійської мови",
        login: "Увійти",
        users: "Користувачі",
        user: "Користувач",
        home: "Головна",
        title:"Назва",
        descr:"Опис",
        available:"Доступно для проходження",
        published:"Опубліковано",
        yes:"Так",
        no:"Ні",
        register: "Реєстрація",
        logOut: "Вийти",
        password: "Пароль",
        level: "Рiвень",
        levels: "Рiвнi",
        score: "Оцiнка",
        quest: 'Питання',
        answer: 'Відповідь',
        variants: 'Варіанти відповідей',
        userTip: 'Відповідь користувача',
        sources: 'Ресурси',
        source: 'Ресурс',
        max: "До максимуму",
        perf: "Успiшнiсть",
        test: "Тест",
        tests: "Тести",
        date: "Дата",
        download: "Завантажити",
        password_more: "Пароль ще раз",
        forgot: "Забули свій пароль?",
        resetPas: "Відновлення паролю",
        reset: "Скинути",
        close: "Закрити",
        remove_ans: "Видалити відповідь",
        save: "Зберігти",
        loading: "Відправка...",
        contact: "Зв'язатися з",
        admin: "адміністратором",
        adm: "Адміністратор",
        blocked: "Заблокований",
        fullName: "ПІБ",
        link: "Посилання",
        links: "Посилання",
        add: "Додати",
        add_answer: "Додати відповідь",
        access_d: "Доступ заборонено",
        info_changed: "Дані успішно змінено",
        info_deleted: "Дані успішно видалено",
        email_sent: "Дані успішно надіслано на Ваш Email",
        error_group: "Оберіть Вашу групу",
        error_auth: 'Помилка! Ви не авторизовані!',
        error_email: 'Введено некоректну Email адресу',
        error_pass_length: "Пароль не повинен бути меншим за 6 символів",
        error_pass_match: "Введені паролі не збігаються.",
        error_confirm_pass: "Підтвердіть пароль",
        error_email_exists: "Така Email адреса вже існує",
        error_no_user: "Користувача з такими даними не існує",
        error_login: "Некоректне ім'я користувача. Спеціальні символи в імені користувача заборонені, або довжина менше 3 символів",
        error_try_later: "Щось пішло не так... Спробуйте пізніше",
        failing: 'Незадовільно',
        satisfactory: 'Задовільно',
        good: 'Добре',
        excellent: 'Відмінно',
        errors: {
            title: "Назва",
            source: "Посилання",
            description: "Опис",
            task: "Завдання",
            answer: "Відповідь",
            username: "Ім\'я користувача",
            email: "Email",
            level: "Рівень",
            password: "Пароль",
            string: '(формат повинен бути строкою)',
            required: 'відсутня',
            name_required: 'відсутнє',
            lev_required: 'відсутнiй',
            incorrect: 'введено некоректно',
            title_string: '@:errors.title @:errors.string',
            source_string: '@:errors.source @:errors.string',
            description_string: '@:errors.description @:errors.string',
            description_required: '@:errors.description @:errors.lev_required',
            source_required: '@:errors.source @:errors.name_required',
            task_string: '@:errors.task @:errors.string',
            answer_string: '@:errors.answer @:errors.string',
            title_required: '@:errors.title @:errors.required',
            username_required: '@:errors.username @:errors.name_required',
            task_required: '@:errors.task @:errors.name_required',
            level_required: '@:errors.level @:errors.lev_required',
            answer_required: '@:errors.answer @:errors.required',
            username_incorrect: '@:errors.username @:errors.incorrect',
            email_incorrect: '@:errors.email @:errors.incorrect',
        }
    },
    ru: {
        welcome: 'Добро пожаловать в систему тестирования!',
        sphere: "Система тестирования по английскому языку",
        information: "Информация",
        start: "Начать тест",
        toTest: 'К тестированию',
        testTopic: 'Тема теста',
        input: 'Вопрос на ввод',
        topics: 'Темы',
        yourGroup: 'Ваша группа',
        group: 'Группа',
        groups: 'Группы',
        choose: 'Выберите Вашу группу и тему теста',
        result: 'Ваш результат:',
        detail: 'Подробнее',
        no_inf: "Нет информации",
        all: "Все",
        name: "Ваше имя",
        userName: "Имя пользователя",
        email: "Ваш Email",
        dashboard: "Панель управления",
        management: "Управление",
        dashboard_welcome: "Добро пожаловать в панель управления сайта. Выберите необходимое действие из меню слева.",
        total_tests: "Всего тестов",
        total_topics: "Всего тем",
        total_links: "Всего ссылок на сторонние ресурсы",
        total_users: "Зарегистрированных пользователей",
        avail_pass: "Доступно для прохождения",
        cancel: "Отменить",
        send: "Отправить",
        userCanNotPass: 'Этот пользователь не может проходить текущий тест',
        attempts: 'Количество попыток',
        attemptsExc: 'Количество попыток для прохождения теста превышено',
        expired: 'Время теста истекло',
        stats: 'Статистика',
        correct: 'Верных',
        correct_ans: 'Верный ответ',
        incorrect: 'Неверных',
        duration: 'Продолжительность',
        show: 'Показать',
        print: 'Печатать',
        grInform: 'Графическая информация',
        average: 'Средняя оценка по уровню:',
        dateTime: 'Дата и время работы',
        notFound: "OOPS! Не найдено",
        notFoundMsg: "К сожалению, запрашиваемая страница не существует",
        return: "Вернуться на главную страницу",
        site_name: "Система тестирования по английскому языку",
        login: "Войти",
        users: "Пользователи",
        user: "Пользователь",
        home: "Главная",
        title:"Название",
        descr:"Описание",
        available:"Доступно для прохождения",
        published:"Опубликовано",
        yes:"Да",
        no:"Нет",
        register: "Регистрация",
        logOut: "Выйти",
        password: "Пароль",
        level: "Уровень",
        levels: "Уровни",
        score: "Оценка",
        quest: 'Вопрос',
        answer: 'Ответ',
        variants: 'Варианты ответов',
        userTip: 'Овет пользователя',
        sources: 'Ресурсы',
        source: 'Ресурс',
        max: "До максимума",
        perf: "Успеваемость",
        test: "Тест",
        tests: "Тесты",
        date: "Дата",
        download: "Скачать",
        password_more: "Пароль еще раз",
        forgot: "Забыли свой пароль?",
        resetPas: "Сбросить пароль",
        reset: "Сбросить",
        close: "Закрыть",
        remove_ans: "Удалить ответ",
        save: "Сохранить",
        loading: "Отправка...",
        contact: "Связаться с",
        admin: "администратором",
        adm: "Администратор",
        blocked: "Заблокирован",
        fullName: "ФИО",
        link: "Ссылка",
        links: "Ссылки",
        add: "Добавить",
        add_answer: "Добавить ответ",
        access_d: "Доступ запрещен",
        info_changed: "Информация успешно изменена",
        info_deleted: "Информация успешно удалена",
        email_sent: "Данные успешно отправлены на Ваш Email",
        error_group: "Выберите Вашу группу",
        error_auth: 'Ошибка! Вы не авторизованы',
        error_email: 'Введен некорректный Email адрес',
        error_pass_length: "Пароль не должен быть менее 6 символов",
        error_pass_match: "Введенные пароли не совпадают.",
        error_confirm_pass: "Подтвердите пароль",
        error_email_exists: "Такой Email адрес уже существует",
        error_no_user: "Пользователя с такими данными не существует",
        error_login: "Некорректное имя пользователя. Специальные символы в имени пользователя запрещены, либо длина менее 3 символов",
        error_try_later: "Что-то пошло не так... Попробуйте позже",
        failing: 'Неудовлетворительно',
        satisfactory: 'Удовлетворительно',
        good: 'Хорошо',
        excellent: 'Отлично',
        errors: {
            title: "Название",
            source: "Ссылка",
            description: "Описание",
            task: "Задание",
            answer: "Овет",
            username: "Имя пользователя",
            email: "Email",
            level: "Уровень",
            password: "Пароль",
            string: '(формат должен быть строкой)',
            required: 'отсутствует',
            incorrect: 'некорректно',
            title_string: '@:errors.title @:errors.string',
            source_string: '@:errors.source @:errors.string',
            description_string: '@:errors.description @:errors.string',
            task_string: '@:errors.task @:errors.string',
            answer_string: '@:errors.answer @:errors.string',
            title_required: '@:errors.title @:errors.required',
            username_required: '@:errors.username @:errors.required',
            source_required: '@:errors.source @:errors.required',
            description_required: '@:errors.description @:errors.required',
            task_required: '@:errors.task @:errors.required',
            level_required: '@:errors.level @:errors.required',
            answer_required: '@:errors.answer @:errors.required',
            username_incorrect: '@:errors.username @:errors.incorrect',
            email_incorrect: '@:errors.email @:errors.incorrect',
        }


    }
}
